### ISSUE TITLE
Usage of Adafruit_ZeroPDM library

### ISSUE THREAD

**Issue by joelguittet** [adafruit/Adafruit_ZeroPDM#1]
Hi,

I'm submitting this issue to ask you how the Adafruit_ZeroPDM library should be used. Do you have example codes using this library ?

I have ported the library in an existing software, reading of I2S data seems to be OK from a MEMS I2S microphone, but I wonder how to treat the data received. The function "i2s_serializer_read_buffer_wait" returns an array, but how to interpret the content ?

My application is -at the moment- a basic sound meter on which I want to indicate on a bar-graph the current ambient noise volume.

Thanks for any example/tuto/video you may have.

Cheers,
Joel

**Comment by ladyada** [comment]
hiya not at this time - this isn't an i2s mic, this is a pdm mic. for i2s please use the I2S arduino library. when we have example code we'll commit it to this repo so if you subscribe to to this repo you'll get notified :)

**Comment by joelguittet** [comment]
Sorry for the mistake, this is a PDM microphone I have, you're right. So no example to use this library at the moment ? What a shame ! I will check it periodically :-)

**Comment by ladyada** [comment]
example has been added
