### ISSUE TITLE
Any chance of a port of this library to nrf52 architecture?

### ISSUE THREAD

**Issue by lambtor** [adafruit/Adafruit_ZeroPDM#6]
Is there any equivalent of this library and Adafruit_ZeroFFT for the bluefruit sense board?  I'm looking to use the PDM on 
[https://learn.adafruit.com/adafruit-feather-sense/](https://learn.adafruit.com/adafruit-feather-sense/)

to display some microphone data.

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_nRF52_Arduino/tree/master/libraries/PDM
is for nrf, zerofft would probably 'just work' because both are ARM cortexm4
