### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by erectcrested** [adafruit/Adafruit_ZeroPDM#8]
Hi.
I am getting the following error when trying to include Zero PDM library:
```
/home/esp32-dev/Arduino/libraries/Adafruit_Zero_PDM_Library/Adafruit_ZeroPDM.cpp:39:53: fatal error: WVariant.h: No such file or directory
 #include "WVariant.h"       // EPioType defined here
^^^
```

How can I solve this? I tried earlier library versions but they didn't work for me either

**Comment by ladyada** [comment]
please provide reproduction details

**Comment by blevlabs** [comment]
The library appears to not have required header files, such as WVariant.h, samd.h, etc seen in the Adafruit_ZeroPDM.cpp file. This is causing issues in the compilation of the example code as these files are not available. Here is one output from trying to compile the example "spipdm_analogout"
`Arduino: 1.8.19 (Linux), Board: "Arduino Nano, ATmega328P"











In file included from /home/blabs/Arduino/libraries/ZeroPDM/Adafruit_ZeroPDM.cpp:39:
/home/blabs/Arduino/libraries/ZeroPDM/WVariant.h:22:10: fatal error: samd.h: No such file or directory
   22 | #include <samd.h>
      |          ^~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Nano.


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by caternuson** [comment]
This library is for SAMD architecture only:
https://github.com/adafruit/Adafruit_ZeroPDM/blob/3a7fbe698d8da8ae9944210ba276ea4c656d10d2/library.properties#L9
(also see readme)

@erectcrested appears you are using an ESP32 (Tensilica)
@blevlabs appears you are using an ATmega328P (AVR)
